#pragma config(Sensor, in4,    light1,         sensorAnalog)
#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Motor,  port2,           swivelMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port7,           blockMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int yellow_high = 2800;
int yellow_low = 2500;
int blue_high = 2000;
int blue_low = 1600;
int red_high = 2400;
int red_low = 2150;
int light_max = 4000;
int noball = 3400;
int waitTime = 1.5;


void sortBalls() {
		if (SensorValue[light1] >= red_low && SensorValue[light1] <= yellow_high) {
			setMotor(swivelMotor, 70);
			setMotor(blockMotor, -70);
			}

		else if (SensorValue[light1] >= 0 && SensorValue[light1] <= blue_high) {
			setMotor(swivelMotor, -70);
			setMotor(blockMotor, -70);
			}
		else {
			setMotor(blockMotor, 0);
			setMotor(swivelMotor, 0);
			}
		}

task main() {

while (1==1) {

	if (SensorValue[light1] <= noball) {
		sortBalls();
		}
	}
}
