#pragma config(Sensor, in5,    light1,         sensorReflection)
#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1==1) {
	if (SensorValue[light1] >= 4000) {
		setMotorSpeed(leftMotor, 127);
		setMotorSpeed(rightMotor, 127);
	}
	else if (SensorValue[light1] <= 250) {
		setMotorSpeed(leftMotor, -127);
		setMotorSpeed(rightMotor, -127);
	}
	else {
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
	}

}


}
