#pragma config(Sensor, in5,    light1,         sensorReflection)
#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

while (1==1) {
	if (SensorValue[limit1] == 1) {
		setMotor(leftMotor, 100); //Set the left Motor speed to 40
		setMotor(rightMotor, 100); //Set the right Motor speed to -40
	}
	else {
		setMotor(leftMotor, 0);
		setMotor(rightMotor, 0);
	}
	if (SensorValue[light1] == 0) {
		setMotorSpeed(rightMotor, 0);
	}

}}
